{"uuid": "8209ab89-7bec-42d0-9840-093e3b477c85", "children": ["c5e418a6-028a-49e5-9c52-4dbd1a9fedd8"], "befores": [{"name": "setup", "status": "passed", "start": 1680239410745, "stop": 1680239416975}], "afters": [{"name": "setup::0", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: disconnected: not connected to DevTools\n  (failed to check if window was closed: disconnected: not connected to DevTools)\n  (Session info: chrome=111.0.5563.147)\nStacktrace:\nBacktrace:\n\t(No symbol) [0x0044DCE3]\n\t(No symbol) [0x003E39D1]\n\t(No symbol) [0x002F4DA8]\n\t(No symbol) [0x002E6DBB]\n\t(No symbol) [0x002E747A]\n\t(No symbol) [0x002E7418]\n\t(No symbol) [0x002DC11A]\n\t(No symbol) [0x002DC977]\n\t(No symbol) [0x003431F8]\n\t(No symbol) [0x0033AE93]\n\t(No symbol) [0x00316F68]\n\t(No symbol) [0x003180CD]\n\tGetHandleVerifier [0x006C3832+2506274]\n\tGetHandleVerifier [0x006F9794+2727300]\n\tGetHandleVerifier [0x006FE36C+2746716]\n\tGetHandleVerifier [0x004F6690+617600]\n\t(No symbol) [0x003EC712]\n\t(No symbol) [0x003F1FF8]\n\t(No symbol) [0x003F20DB]\n\t(No symbol) [0x003FC63B]\n\tBaseThreadInitThunk [0x76B87D69+25]\n\tRtlInitializeExceptionChain [0x770CB74B+107]\n\tRtlClearBits [0x770CB6CF+191]\n\n", "trace": "  File \"C:\\Users\\MASH\\PycharmProjects\\Test_ZamitProject\\venv\\lib\\site-packages\\allure_commons\\_allure.py\", line 221, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"C:\\Users\\MASH\\PycharmProjects\\Test_ZamitProject\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 917, in _teardown_yield_fixture\n    next(it)\n  File \"C:\\Users\\MASH\\PycharmProjects\\Test_ZamitProject\\testCases\\conftest.py\", line 13, in setup\n    request.cls.driver.close()\n  File \"C:\\Users\\MASH\\PycharmProjects\\Test_ZamitProject\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 551, in close\n    self.execute(Command.CLOSE)\n  File \"C:\\Users\\MASH\\PycharmProjects\\Test_ZamitProject\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 440, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\MASH\\PycharmProjects\\Test_ZamitProject\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 245, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1680239423509, "stop": 1680239423514}], "start": 1680239410745, "stop": 1680239423514}